### ISSUE TITLE
Error  when logging in :(

### ISSUE THREAD

**Issue by vuruba** [FailcoderAddons/supervillain-ui#62] opened 2016-11-30 08:09 UTC
Unfortunately I tried everything. New Installed. Everything cleared. But always I have when I log or reload this error: see picture
![wowscrnshot_113016_090506](https://cloud.githubusercontent.com/assets/22202989/20744491/9235c7f4-b6dc-11e6-8068-fdf4b3f3f153.jpg)

Am also not alone with the error. 2 friends also have this error takes.

**Comment by prom3theu5** [comment] 2016-11-30 08:29
Also have this. Doesn't appear to cause any issues. I have tried disabling raid and party frames, as I use **Vuhdo** for groups anyhow. no go. Still does it.

**Comment by vuruba** [comment] 2016-11-30 11:11
Have already tried everything. It just annoys totally. The message comes with login, use resting stone, umspecc and and and...:(

**Comment by TheRedBull** [comment] 2016-12-30 08:03
When anyone feels like taking another stab at this, will you please go into the UI Options and report the version you have installed?

**Comment by joeymagz** [comment] 2017-08-14 22:40
Closing issue since no one has reported this again since December and I cannot reproduce the error.

**Closed by joeymagz** 2017-08-14 22:40 UTC
Labels: can't reproduce
