### ISSUE TITLE
QuestTracker Error

### ISSUE THREAD

**Issue by TheRedBull** [FailcoderAddons/supervillain-ui#64] opened 2016-12-27 17:33 UTC
Got this error when I had a new 'click to complete' quest finish. In this instance, this was the quest "[Moving On](http://www.wowhead.com/quest=30648/moving-on)"

Copied from BugGrabber:

QuestTracker [QUEST_LOG_UPDATE]: @(12/27/16 10:27:42) - ...rface\AddOns\SVUI_QuestTracker\SVUI_QuestTracker.lua:372: Usage: SVUI_QuestTrackerScrollFrameScrollBar:SetMinMaxValues(min, max)

**Comment by TheRedBull** [comment] 2016-12-29 02:45
I was able to mitigate this error by uncommenting line 373, but there is no pop-up showing when a 'click to complete' quest finishes. In this case, I finished "[Of Fire and Thunder](http://www.wowhead.com/quest=33013/of-fire-and-thunder)" and no on-screen notice appeared.

As I'm new to this UI addon, I don't know that an on-screen notification should be displayed, but I would assume such as that is part of the default UI.

**Comment by finalsliver** [comment] 2016-12-29 14:30
I believe auto popups are disabled in favour of a highlighted bar appearing at the top of the quest panel in the bottom right docket. 

Development has slowed for now as both devs have a busy workload. Most of us keeping an eye on things are connected on the Discord channel. feel free to join us there. not much activity at the moment but when things popup we discuss them and help as we can :) link below.

https://discord.gg/58AcatX

**Comment by TheRedBull** [comment] 2016-12-30 08:13
Thanks @finalsliver I've joined :)

As for this issue, I'm going to leave this open for the time being, but my workaround is still working well after another 5 or 6 'click to complete' quests

**Comment by joeymagz** [comment] 2017-09-03 23:23
I can't reproduce this error in the latest commit and the error is very old. I am closing this.

**Closed by joeymagz** 2017-09-03 23:23 UTC
Labels: can't reproduce, very old/closing
