### ISSUE TITLE
Mac Issues

### ISSUE THREAD

**Issue by jemoreno** [FailcoderAddons/supervillain-ui#34] opened 2016-11-02 17:35 UTC
SKINS [CUSTOM_SYSTEM]: @(11/02/16 12:34:45) - ...ace\AddOns\SVUI_Skins\components\blizzard\system.lua:591: attempt to index local 'MacOptionsFrame' (a nil value)

**Comment by joev** [comment] 2016-11-02 17:50
duplicate of #25

**Closed by joev** 2016-11-02 17:50 UTC
Labels: duplicate
