### ISSUE TITLE
LUA error 2

### ISSUE THREAD

**Issue by klepp0906** [FailcoderAddons/supervillain-ui#18] opened 2016-10-28 10:52 UTC
also getting this popping up on log in and every load thereafter 

SKINS [Blizzard_GuildUI]: @(10/27/16 18:55:49) - ...face\AddOns\SVUI_Skins\components\blizzard\guild.lua:524: attempt to call method 'SetStyle' (a nil value)

**Comment by joev** [comment] 2016-10-30 13:27
Duplicate of #12

**Closed by joev** 2016-10-30 13:27 UTC
Labels: duplicate
